"""B-28 Phase 5 — PHASE 0 IN THE PRODUCT: the mandatory Kickoff.

A chat-mode state machine that runs the 8 blocks (A produit → H pre-mortem) of
JOAO_PHASE0_PROTOCOL.md: short questions ONE AT A TIME, answers stored progressively.
Block H (the pre-mortem) is generated by the Phase-2 selector — the 10 known ways this
kind of project has already failed. Output: projects/<name>/PROJECT_SPEC.md + ROADMAP.md
+ PROJECT_MEMORY.md.

The spec is born UNSIGNED (`SIGNÉ : ❌ EN ATTENTE`). Only an explicit Boss action —
`sign()`, the "GO Boss" button — writes `SIGNÉ : ✅ GO Boss — <date>`. It is NEVER
auto-signed (silence ≠ GO, LOI 1). The mission launcher hard-refuses any build on a
project whose spec is missing or unsigned.
"""
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from ..storage.atomic import atomic_write_json, atomic_write_text


def _memory_dir() -> Path:
    override = os.environ.get("JOAO_MEMORY_DIR")
    return Path(override).expanduser() if override else Path(__file__).resolve().parents[3] / "memory"


def _selector():
    mem = _memory_dir()
    if (mem / "select_lessons.py").exists():
        if str(mem) not in sys.path:
            sys.path.insert(0, str(mem))
        import select_lessons  # noqa: PLC0415
        return select_lessons
    return None


@dataclass(frozen=True)
class Question:
    block: str
    key: str
    text: str


# The interview — verbatim intent of JOAO_PHASE0_PROTOCOL.md §1, blocks A–G.
# Block H (pre-mortem) is generated, not asked.
QUESTIONS: list[Question] = [
    Question("A", "A1", "En UNE phrase : ce produit fait quoi, pour qui ?"),
    Question("A", "A2", "Le problème exact qu'il tue — et comment tu le résous AUJOURD'HUI sans lui ?"),
    Question("A", "A3", "Succès = quoi, mesurable, dans 30 jours ?"),
    Question("A", "A4", "Qu'est-ce qui te ferait dire « c'est de la merde » même si tout marche techniquement ?"),
    Question("B", "B1", "Liste des artefacts visuels/formats du produit (docs, UI, emails, exports…)."),
    Question("B", "B2", "Pour CHACUN : une référence existe-t-elle à valider sur rendu AVANT le build ?"),
    Question("B", "B3", "Chaque autorité validée = fichier + sha256 + date du GO. Lesquelles sont prêtes ?"),
    Question("C", "C1", "Lister TOUTES les décisions que le système prendra seul (filtres, seuils, éligibilité, priorités, montants)."),
    Question("C", "C2", "Chaque règle reformulée en test binaire (« si X explicite → oui, sinon → non ») — tranche-les."),
    Question("C", "C3", "Valeurs par défaut et cas limites (vide, ambigu, contradictoire) : décide-les ici."),
    Question("D", "D1", "Inputs → traitements → outputs : le schéma de flux en 10 lignes max."),
    Question("D", "D2", "LES INTERDITS ABSOLUS : ce que le système ne doit JAMAIS faire même si c'est plus simple."),
    Question("D", "D3", "Ce qui est append-only / immuable / signé."),
    Question("D", "D4", "Les données sensibles et où elles vivent (jamais commitées)."),
    Question("E", "E1", "Casting IA : qui build (volume), qui review (adversarial), qui audite — builder ≠ reviewer sur le chemin critique."),
    Question("E", "E2", "Stack + environnement cible + dépendances système à installer/vérifier AU DÉBUT."),
    Question("E", "E3", "Budget : coût cible par run, modèle par défaut, quand escalader."),
    Question("E", "E4", "Découpage en missions BORNÉES (jamais une session à 100% de contexte)."),
    Question("F", "F1", "Definition of Done par livrable, TESTABLE (commande, clic, rendu — pas « ça a l'air bon »)."),
    Question("F", "F2", "L'évidence exigée : side-by-side rendu↔autorité (L8), section NON VÉRIFIÉ (L9), preuves d'exécution."),
    Question("F", "F3", "Ce qui BLOQUE techniquement (hash de dérivation, gates fail-closed) vs ce qui alerte seulement."),
    Question("F", "F4", "Qui juge quoi : le Boss juge le RENDU aux jalons ; il ne debugge jamais."),
    Question("G", "G1", "V0 = le plus petit truc UTILISABLE. En vrai usage en combien de runs ?"),
    Question("G", "G2", "Jalons V0→V1 : pour chacun livrable + gate + décision Boss attendue."),
    Question("G", "G3", "HORS-SCOPE V1 explicite (ce qu'on ne fait PAS)."),
    Question("G", "G4", "Dépendances externes (secrets, comptes, quotas, actions Boss) + date butoir."),
]

SIGNED_PENDING = "SIGNÉ : ❌ EN ATTENTE"
SIGNED_RE = re.compile(r"^SIGNÉ\s*:\s*✅\s*GO Boss", re.M)


def spec_path(projects_root: Path, project: str) -> Path:
    return Path(projects_root) / project / "PROJECT_SPEC.md"


def spec_is_signed(projects_root: Path, project: str) -> bool:
    path = spec_path(projects_root, project)
    return path.is_file() and bool(SIGNED_RE.search(path.read_text()))


class KickoffError(RuntimeError):
    pass


class Kickoff:
    """Progressive Phase-0 interview → signed PROJECT_SPEC + ROADMAP + PROJECT_MEMORY."""

    def __init__(self, projects_root: Path):
        self.root = Path(projects_root)

    def _dir(self, project: str) -> Path:
        return self.root / project

    def _state_path(self, project: str) -> Path:
        return self._dir(project) / "kickoff.json"

    def _load(self, project: str) -> dict:
        path = self._state_path(project)
        if not path.exists():
            raise KickoffError(f"no kickoff in progress for {project!r} — call start() first")
        return json.loads(path.read_text())

    def _save(self, project: str, state: dict) -> None:
        atomic_write_json(self._state_path(project), state)

    def start(self, project: str) -> dict:
        self._dir(project).mkdir(parents=True, exist_ok=True)
        state = {"schema_version": 1, "project": project, "answers": {}, "cursor": 0}
        self._save(project, state)
        return state

    def current_question(self, project: str) -> Question | None:
        state = self._load(project)
        i = state["cursor"]
        return QUESTIONS[i] if i < len(QUESTIONS) else None

    def interview_complete(self, project: str) -> bool:
        return self._load(project)["cursor"] >= len(QUESTIONS)

    def answer(self, project: str, text: str) -> dict:
        state = self._load(project)
        i = state["cursor"]
        if i >= len(QUESTIONS):
            raise KickoffError("interview already complete")
        state["answers"][QUESTIONS[i].key] = text.strip()
        state["cursor"] = i + 1
        self._save(project, state)
        if state["cursor"] >= len(QUESTIONS):
            self._generate(project, state)
        return state

    # ── pre-mortem (block H) — generated by the Phase-2 selector ──
    def premortem(self, project: str, answers: dict) -> list[dict]:
        sel = _selector()
        if sel is None:
            return []
        mission_type = " ".join(answers.get(k, "") for k in ("A1", "A2", "B1", "B2", "D1", "D2"))
        return sel.select_lessons(project="", mission_type=mission_type, max_tokens=800,
                                  max_k=10, lessons=sel.load_lessons())

    def _generate(self, project: str, state: dict, *, date_str: str = "") -> None:
        answers = state["answers"]
        pm = self.premortem(project, answers)
        folder = self._dir(project)
        atomic_write_text(folder / "PROJECT_SPEC.md", self._render_spec(project, answers, pm, date_str))
        atomic_write_text(folder / "ROADMAP.md", self._render_roadmap(project, answers))
        atomic_write_text(folder / "PROJECT_MEMORY.md", self._render_memory(project, answers, pm))

    def _qa(self, answers: dict, *keys: str) -> str:
        by_key = {q.key: q for q in QUESTIONS}
        return "\n".join(f"- **{k}. {by_key[k].text}**\n  {answers.get(k, '<sans réponse>')}" for k in keys)

    def _render_spec(self, project: str, answers: dict, pm: list[dict], date_str: str) -> str:
        version = "v1.0"
        premortem = "\n".join(f"{i}. [{d['source_defect']}] {d['rule']}  → parade dans la spec ?"
                              for i, d in enumerate(pm, 1)) or "_(sélecteur de pré-mortem indisponible)_"
        return (
            f"# PROJECT_SPEC — {project} · {version} · {date_str or '<date>'}\n"
            f"{SIGNED_PENDING}\n\n"
            f"## 1. PRODUIT\n{self._qa(answers, 'A1', 'A2', 'A3', 'A4')}\n\n"
            f"## 2. AUTORITÉS\n{self._qa(answers, 'B1', 'B2', 'B3')}\n\n"
            f"## 3. RÈGLES BINAIRES\n{self._qa(answers, 'C1', 'C2', 'C3')}\n\n"
            f"## 4. FONCTIONNEMENT\n{self._qa(answers, 'D1', 'D2', 'D3', 'D4')}\n\n"
            f"## 5. BUILD\n{self._qa(answers, 'E1', 'E2', 'E3', 'E4')}\n\n"
            f"## 6. GATES\n{self._qa(answers, 'F1', 'F2', 'F3', 'F4')}\n\n"
            f"## 7. HORS-SCOPE V1\n{self._qa(answers, 'G3')}\n\n"
            f"## 8. PRE-MORTEM (10 échecs connus → parade dans la spec)\n{premortem}\n\n"
            f"## AVENANTS\n_(aucun)_\n"
        )

    def _render_roadmap(self, project: str, answers: dict) -> str:
        return (
            f"# ROADMAP — {project} · générée depuis PROJECT_SPEC v1.0\n\n"
            f"V0 (utilisable) : {answers.get('G1', '<...>')}\n\n"
            f"Jalons V0→V1 :\n{answers.get('G2', '<...>')}\n\n"
            f"HORS-SCOPE V1 : {answers.get('G3', '<...>')}\n\n"
            f"Dépendances externes (+ butoir) : {answers.get('G4', '<...>')}\n\n"
            f"_Chaque jalon fini = rétro L7 + update PROJECT_MEMORY + (si écart) avenant spec._\n"
        )

    def _render_memory(self, project: str, answers: dict, pm: list[dict]) -> str:
        lessons = "\n".join(f"- [{d['source_defect']}] {d['rule']}" for d in pm) or "_(aucune)_"
        return (
            f"# PROJECT_MEMORY — {project}\n"
            f"_Injecté en entête de CHAQUE mission du projet. Mis à jour à chaque rétro/décision Boss._\n\n"
            f"## Autorités (à valider sur rendu)\n{answers.get('B1', '<...>')}\n\n"
            f"## Décisions binaires (verbatim Boss)\n{answers.get('C2', '<...>')}\n\n"
            f"## Interdits absolus\n{answers.get('D2', '<...>')}\n\n"
            f"## Leçons du pré-mortem (mémoire JOÃO)\n{lessons}\n"
        )

    # ── signature — explicit Boss action only, never automatic ──
    def sign(self, project: str, *, date_str: str) -> Path:
        path = spec_path(self.root, project)
        if not path.is_file():
            raise KickoffError(f"no PROJECT_SPEC to sign for {project!r} — finish the Kickoff first")
        text = path.read_text()
        if SIGNED_RE.search(text):
            return path
        if SIGNED_PENDING not in text:
            raise KickoffError("PROJECT_SPEC has no signature line to update")
        atomic_write_text(path, text.replace(SIGNED_PENDING, f"SIGNÉ : ✅ GO Boss — {date_str}"))
        return path

    def is_signed(self, project: str) -> bool:
        return spec_is_signed(self.root, project)
